---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jira-share-pvc  
  labels:
    app: jira-share
spec:
  accessModes:
  - ReadWriteMany      
  resources:
     requests:
       storage: 3Gi
